name: Build and push docker image

on:
  push:
    branches:
      - master
      - '[0-9]+-*'
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: print all environment variables
        run: env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push on git tag event
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Build and push on git push to branch
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
