name: Build and push docker image

on: push
  # push:
  #   branches:
  #     - master
  #     - '[0-9]+-*'
  #   tags: [ '*.*.*' ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: print all environment variables
        run: env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push on git tag event
        if: github.GITHUB_REF_TYPE == 'tag'
        uses: docker/build-push-action@v3
        with:
          build-args: DADA2_COMMIT=v1.18
          context: "{{defaultContext}}:docker"
          push: true
          tags: |
            ghcr.io/nhoffman/dada2-nf:latest
            ghcr.io/nhoffman/dada2-nf:${{ github.GITHUB_REF_NAME }}

      - name: Build and push on git push to branch
        # if: github.GITHUB_REF_TYPE == 'branch'
        uses: docker/build-push-action@v3
        with:
          build-args: DADA2_COMMIT=v1.18
          context: "{{defaultContext}}:docker"
          push: true
          tags: |
            ghcr.io/nhoffman/dada2-nf:${{ github.GITHUB_REF_NAME }}

