name: Build and push docker image from tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '.+-rc[0-9]'

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: print all environment variables
        run: env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push on git tag event
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
