name: Run pipeline tests on PRs

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nhoffman/dada2-nf:latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: |
        cd /usr/local/bin/
        wget -qO - https://github.com/nextflow-io/nextflow/releases/download/v22.10.8/nextflow | bash
    - run: nextflow -quiet run main.nf -params-file test/minimal/params.json -without-docker -profile local
    - run: nextflow -quiet run main.nf -params-file test/its/params.json -without-docker -profile local
    - run: nextflow -quiet run main.nf -params-file test/noindex/params.json -without-docker -profile local
    - run: nextflow -quiet run main.nf -params-file test/single/cmsearch/params.json -without-docker -profile local
    - run: nextflow -quiet run main.nf -params-file test/single/vsearch/params.json -without-docker -profile local

    - run: nextflow -quiet run main.nf -params-file test/minimal/params.json -without-docker -profile local --manifest test/minimal/manifest.csv
    - run: nextflow -quiet run main.nf -params-file test/its/params.json -without-docker -profile local --manifest test/its/manifest.csv
    - run: nextflow -quiet run main.nf -params-file test/noindex/params.json -without-docker -profile local --manifest test/noindex/manifest.csv
    - run: nextflow -quiet run main.nf -params-file test/single/cmsearch/params.json -without-docker -profile local --manifest test/single/manifest.csv
    - run: nextflow -quiet run main.nf -params-file test/single/vsearch/params.json -without-docker -profile local --manifest test/single/manifest.csv

    - run: |
        cd test/ungs/
        ./test_combine_svs.sh
