name: Run dada2-nf test runs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nhoffman/dada2-nf:latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: |
        cd /usr/local/bin/
        wget -qO - https://get.nextflow.io | bash
    - run: nextflow -quiet run main.nf -params-file params-minimal.json -without-docker
    - run: nextflow -quiet run main.nf -params-file params-its.json -without-docker
    - run: nextflow -quiet run main.nf -params-file params-noindex.json -without-docker
    - run: nextflow -quiet run main.nf -params-file params-single-cmsearch.json -without-docker
    - run: nextflow -quiet run main.nf -params-file params-single-vsearch.json -without-docker
    - run: cmp --silent output-cmsearch/counts.csv output-vsearch/counts.csv


