name: Run dada2-nf test run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nghoffman/dada2-nf:v1.15
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: |
        cd /usr/local/bin/
        wget -qO - https://get.nextflow.io | bash
    - run: nextflow -quiet run main.nf -params-file params-minimal.json -without-docker
