name: Run pipeline tests and deploy to registry

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '.+-rc[0-9]'
  pull_request:
    branches:
      - 'master'
  release:
    types:
      - published
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test_and_publish:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v4
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: |
          latest=false
        tags: |
          type=ref,event=tag

    - name: Build Docker image
      uses: docker/build-push-action@v7
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: "{{defaultContext}}:docker"
        labels: ${{ steps.meta.outputs.labels }}
        load: true
        push: false
        tags: |
          ${{ steps.meta.outputs.tags }}
          gha_image

    - name: Install Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Nextflow
      uses: nf-core/setup-nextflow@v3
      with:
        version: latest

    # test run_tests.sh script
    - run: ./test/run_tests.sh -- -profile docker --container gha_image

    # test manifest files using --manifest override arg
    - run: |
        nextflow -quiet run main.nf -params-file test/minimal/params.json -profile docker --container gha_image --manifest test/minimal/manifest.csv
        cd output-minimal/ && sha256sum -c ../test/minimal/base-files.sha256
    - run: |
        nextflow -quiet run main.nf -params-file test/its/params.json -profile docker --container gha_image --manifest test/its/manifest.csv
        cd output-its/ && sha256sum -c ../test/its/base-files.sha256
    - run: |
        nextflow -quiet run main.nf -params-file test/noindex/params.json -profile docker --container gha_image --manifest test/noindex/manifest.csv
        cd output-noindex/ && sha256sum -c ../test/noindex/base-files.sha256
    - run: |
        nextflow -quiet run main.nf -params-file test/single/cmsearch/params.json -profile docker --container gha_image --manifest test/single/manifest.csv
        cd output-cmsearch/ && sha256sum -c ../test/single/cmsearch/base-files.sha256
    - run: |
        nextflow -quiet run main.nf -params-file test/single/vsearch/params.json -profile docker --container gha_image --manifest test/single/manifest.csv
        cd output-vsearch/ && sha256sum -c ../test/single/vsearch/base-files.sha256
    - run: docker run --volume $(pwd):$(pwd) --workdir $(pwd) gha_image /bin/bash -c "cd test/ungs/;./test_combine_svs.sh"

    - name: Push release to ${{ env.REGISTRY }}
      if: github.ref_type == 'tag'
      uses: docker/build-push-action@v7
      with:
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: "{{defaultContext}}:docker"
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  tag_latest:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v4
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Retag release image as latest
      run: |
        docker buildx imagetools create \
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
